apiVersion: v2
name: weir
description: Synchronous MongoDB and Search data plane
type: application
version: 0.3.0
appVersion: "db64258cd48a"
annotations:
  weir.batchstream.io/source-revision: "db64258cd48a047d94180c10e9fc2069ea934c1d"
kubeVersion: ">=1.30.0-0"
home: https://github.com/batchstream/weir
sources:
  - https://github.com/batchstream/weir-charts
  - https://github.com/batchstream/weir
