{{- include "weir.validate" . -}}
{{- if .Values.config.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weir.fullname" . }}
  labels:
    {{- include "weir.labels" . | nindent 4 }}
data:
  node.yaml: |
    {{- .Values.config.data.node | toYaml | nindent 4 }}
  routes.yaml: |
    {{- .Values.config.data.routes | toYaml | nindent 4 }}
{{- end }}
