apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "weir.fullname" . | trunc 54 | trimSuffix "-") }}
  labels:
    {{- include "weir.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "weir.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      appProtocol: kubernetes.io/h2c
