{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "weir.fullname" . }}-metrics
  labels:
    {{- include "weir.labels" . | nindent 4 }}
  {{- with .Values.metrics.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "weir.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.diagnostics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
